version: '3'

services:
  web:
    build: .
    volumes:
      - .:/app
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development
    env_file:
      - .env
    ports:
      - "8081:8081"
